### ISSUE TITLE
Cannot get Demo to run

### ISSUE THREAD

**Issue by mccare** [baianat/hooper#26]
**Describe the bug**
The simple slider demo just displays boxes, no slides

**To Reproduce**
vue-cli 3.3.0

vue create slider 
cd slider
npm install hooper
edit HelloWorld.vue and replace most of the template with
```html
   <hooper>
      <slide>
        1
      </slide>
     <slide>
        2
      </slide>
     <slide>
        3
      </slide>
     <slide>
        4
      </slide>
    </hooper>
```
(and add the import and component stuff for Hooper and Slide)

**Expected behavior**
I would expect to see one "slide" with one number and that I could then scroll through the rest of the slides. 

**Screenshots**
<img width="756" alt="screenshot 2019-01-29 at 20 09 18" src="https://user-images.githubusercontent.com/2522744/51933515-c6c6df00-2401-11e9-9bfa-f5251d683418.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.2
 - Browser Chrome
 - Version 71

**Additional context**
I've tried the demo, too, but same behaviour. Don't know what I'm missing...

**Comment by Abdelrahman3D** [comment]
For your problem, I think you need to include the stylesheet file (hoopoe.css), and everything will work just fine.

**Comment by mccare** [comment]
Yes, got it! I've created a very small PR to fix this in the docs.
Btw, the standard vue-cli template will have 
```css
li { margin: 0 10px }
``` 
in the style section (for the HelloWorld.vue). This the produces a slider that 'moves to the right' on each slide since the elements on the left still have some space (the margin namely) and hooper uses the li element for slider. Maybe clear the li elements in hooper.css of formatting so no side effects of existing formating will be there?

**Comment by lupodellasleppa** [comment]
Appears to be still an issue, looks like the css its not getting loaded properly.
**Describe the bug**
No styling (colors, shapes) on elements
**To reproduce**
I tried to use it on a project of mine and didn't work, so I created a virgin project with vue-cli create and replaced `App.vue` with the example in the documentation and the issue is still there.
**Expected behavior**
I expect to see some sort of styling but there appears to be none, or maybe not all of it.
**Screenshots**
Page with two slide elements as in the doc example. Opening the page shows `slide 1` spanning through the entire width of the view.
![image](https://user-images.githubusercontent.com/23663689/93715745-7cace700-fb6b-11ea-8bcd-29bf30ea71b0.png)
Scrolling/dragging brings `slide 2`, however no styiling
![image](https://user-images.githubusercontent.com/23663689/93715750-833b5e80-fb6b-11ea-9b6e-ae8834be0b29.png)
**Desktop:**
OS: Ubuntu 18.04
Browser: Chrome
Version: 85.0.4183.102
**Additional context**
Scrolls and mouse drags are working fine and without importing the css all I see is a list so I would guess something is happening but not properly.

This is my project configuration:
```
{
  "name": "test-hooper",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "hooper": "^0.3.1",
    "vue": "^2.6.11",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "vue-template-compiler": "^2.6.11"
  }
}
```

I've also tried with version `0.3.4` which is the one that gets installed by `npm install hooper`, however github lists `0.3.1` as latest release so I also gave a try to that one.

Is this the expected behavior? I was expecting to have some styling as shown in the examples page
