### ISSUE TITLE
Nuxtjs

### ISSUE THREAD

**Issue by brunosilvafranca** [baianat/hooper#5]
Sorry my english!

Please, would you like to add compatibility with nuxtjs ssr?
I know it works if you use <no-ssr></no-ssr>

**Comment by Abdelrahman3D** [comment]
Hooper will work well with Nuxt.js and Universal Apps. However, the carousel component is not SSR friendly by its natural; because it intensively depends on `window`, `document`, and `view-port` size. so main Hooper calculations are executed inside client-only lifecycle *mounted* hook.

**Comment by brunosilvafranca** [comment]
thanks for listening

**Comment by DreaMinder** [comment]
@Abdelrahman3D but it doesn't mean that SSR should be ignored, right? I've been struggling with vue-agile, vue-carousel and awesome-swiper for a year and it looks like this carousel is much better than all of them. SSR-support - one thing left to make it ideal.
If I'll figure it out, will you approove my PR?

I can see 2 cases
1. jquery-style. Render slides as-is, with only css applied, in this case while js is not initlaised, slider will be shown as list of blocks, But at least it can be indexed. Just need to make a condition to enable js only on client or make directives instead of components like awesome-swiper did
2. first-slider-placeholder. Same as point 1, but this time only first slide renders on server. This way design won't be messed up. I use this approach with no-ssr  placeholder and vue-carousel - works well. But as far as I understand there is no good way to bypass no-ssr dependency to inside of your component.

**Comment by DreaMinder** [comment]
```
<template>
  <hooper>
    <no-ssr>
      <slide slot='placeholder' ssr>
        slide 1
      </slide>

      <slide>
        slide 1
      </slide>
      <slide>
        slide 2
      </slide>
    </no-ssr>
  </hooper>
</template>
```

what I mean is something like this. SSR flag turns off any document interatcions. Or if there slots conflict, use this:

```
<template>
  <div>
    <no-ssr>
      <hooper slot="placeholder">
        <slide ssr>
          slide 1
        </slide>
      </hooper>
      <hooper>
        <slide>
          slide 1
        </slide>
        <slide>
          slide 2
        </slide>
      </hooper>
    </no-ssr>
  </div>
</template>
```

Just need to make SSR flag. Or maybe its already done? I mean I copied your sources and launched them like this:
```
import { Hooper, Slide } from '@/src/index.js';
```
SSR works with code above this way

**Comment by logaretm** [comment]
@DreaMinder I don't think hooper itself uses any browser related environment before the mounted hook so It should be working fine with SSR.

I believe the issue is that the default CSS isn't being extracted to a separate bundle, causing the `document` undefined issue. That is because it tries to inject the styles to the `document`'s `head` element.

I have created a PR #8 that addresses this issue, It allows the content to be indexed like your first suggestion.

Maybe later we could implement sensible defaults based on the props provided, making the initial render as close as possible to the end result.
