### ISSUE TITLE
Slides disappear on assigning variable with infiniteScroll on

### ISSUE THREAD

**Issue by jflaflamme** [baianat/hooper#71]
**Describe the bug**
when images are async, a simple click function assigning a variable making them disappear.

- Slides do not disappear if InfiniteScroll set to false

 - Version [0.1.2]

**Comment by Abdelrahman3D** [comment]
Please provide me with steps to reproduce the bug, with the expected and results.

**Comment by BryanKuiper** [comment]
I noticed that this happens because the ```transform``` style on the hooper-track does not change back to ```transform: translate(0px, 0px);``` but instead continues to decrease the x-coordinate far beyond the last slide. This seems to happen after something in the slides is changed (for instance a variable or the height/width of the slides for different viewports). I changed itemsToShow in the settings dynamically depending on the viewport's width.

I currently do not have a code example for you since I have implemented it in my website. If you need it, I will try to find some time to make one.

Hope this helps.

**Comment by 555ea** [comment]
@Abdelrahman3D Unfortunatelly this is still true on 0.1.5, The slides disappear when parent re-renders and appear back again with the next autoPlay slide change. 

I've made a codepen for you https://codepen.io/anon/pen/gJgyjR If you click on increase - you can see that the current slide dissapears and on the next tick you can see next slide.

Is there a workaround to this? Although it's better now, than before, I would like the slides not to disappear. Calling this.$refs.hooper .reset() and .update() has no result, current slide disappears

**Comment by 555ea** [comment]
As a temporary hotfix, I'm able to run this.$refs.hooper.slideNext();, this way clones re-appear but there is still a white blink

**Comment by Abdelrahman3D** [comment]
Okay, let's reopen this issue for now, and make more investigations on this.

**Comment by logaretm** [comment]
I tested this against #104 and it seems to be working fine. 

![test](https://user-images.githubusercontent.com/6261322/60384991-7de48680-9a84-11e9-94e5-73adecfbde3c.gif)
