### ISSUE TITLE
Infinite Scroll slider was not correct when changed a language with vue-i18n plugin.

### ISSUE THREAD

**Issue by imjeen** [baianat/hooper#72]
Firstly, thanks for the slider, it is very good.

**Describe the bug**

Recently I use the hooper width the [vue-i18n](https://kazupon.github.io/vue-i18n/guide/locale.html) plugin, and I make the slider setting width the `settings` prop, see bellow: 
```
{
      infiniteScroll: true,
      autoPlay: true,
      playSpeed: 3000,
      wheelControl: false,
}
```
When change the language, the clone item was lost. see the[ example (codepen)](https://codepen.io/anon/pen/rbPvzd)

**To Reproduce**
1. Set  `infiniteScroll=true`
2. Change the language

the items of  Infinite Scroll slider were disappeared.

**Expected behavior**
Only change a component local language, the slider should be normal.

**Screenshots**
see the[ example (codepen)](https://codepen.io/anon/pen/rbPvzd)

**Desktop (please complete the following information):**
 - OS: macOS@10.14.4 
 - Browser:  chrome@73

**Smartphone (please complete the following information):**

**Additional context**
- vue@2.6.10
- vue-i18n@8.11.1
- hooper@0.1.2

**Comment by Abdelrahman3D** [comment]
This happens because *Vuei18n* uses [$forceUpdate](https://github.com/kazupon/vue-i18n/blob/4aecf0329dbb8cb0e19e0cfbfe8fb7b3e5737f8e/src/index.js#L210) to update all translations when the local changes, Which conflicts with Hooper's cloned slides and cause them not to re-render again. We will investigate more on this, and try to fix it from our side.
