### ISSUE TITLE
Pagination indicators and slide count

### ISSUE THREAD

**Issue by trank2012** [baianat/hooper#83]
**Is your feature request related to a problem? Please describe.**
I made slider with 6 items to show (itemsToShow: 6) , and slide this 6 items at once (Items ToSlide: 6). So if we have 24 items, actualy we dont need to show 24 hooper indicators, just 4 of them will be enough, because we slide 6 items at once.
**Describe the solution you'd like**
If we have 'n' items in slide, we need to calculate it like an one slide item.

**Comment by DavidRouyer** [comment]
I've created a PR (#82), because I have the same kind of problem with the "Next" button

**Comment by Abdelrahman3D** [comment]
Here is the thing, If I have a carousel slider with 4 `itemsToShow` and 3 `itemsToSlide`, this feature will be broken in this case, moreover this also will not be valid in the cause of dragging, since drag ignores the `itemsToSlide` porp and restores the carousel to the nearest suitable position.

I agree that in your use case it would be better to add a few indicators as possible, but we can't support this from our side since it would be broken in many scenarios.

What great about `Hooper` is that it's a component-based, you can add any component you want adding new behavior. I do encourage you to clone [hooper-paggination](https://github.com/baianat/hooper/blob/master/src/addons/Pagination.vue) component and add the desired behavior to it, and we are glad to help you with this.

**Comment by trank2012** [comment]
> Here is the thing, If I have a carousel slider with 4 `itemsToShow` and 3 `itemsToSlide`, this feature will be broken in this case, moreover this also will not be valid in the cause of dragging, since drag ignores the `itemsToSlide` prop and restores the carousel to the nearest suitable position.
> 
> I agree that in your use case it would be better to add a few indicators as possible, but we can't support this from our side since it would be broken in many scenarios.
> 
> What great about `Hooper` is that it's a component-based, you can add any component you want adding new behavior. I do encourage you to clone [hooper-paggination](https://github.com/baianat/hooper/blob/master/src/addons/Pagination.vue) component and add the desired behavior to it, and we are glad to help you with this.

Yeah, its make sense. Thank you

**Comment by circularcube** [comment]
I worked out you can do this just with CSS by hiding the unwanted pagination indicators. 

For example if you display 6 slides, and slide 6 items then you can use this:

```
.hooper-indicators li button {
  display: none;
}
.hooper-indicators li:nth-child(6n+1) button {
  display: inline;
}
```

For 4 slides, change 6n+1 to 4n+1 etc.

The CSS is first hiding all hooper-indicator items, and then re-displaying only the ones that correspond to the first slide of each block of slides.

UPDATE: on further testing I realise the pagination gets out of sync with this method as hooper scrolls an extra slide at the end so if you get to the end and work back then the dots wont highlight as expected.
